# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-08-07 08:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20170804_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 8, 53, 42, 84436, tzinfo=utc)),
        ),
    ]
